# Question 1:
Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [4]:
import numpy as np

a=np.array([1,2,3,4])
b=np.array([2,1,4,3])
c=a>b
c

array([False,  True, False,  True])

# Question 2:
Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [105]:
array_zeros = np.zeros((10),dtype=np.ushort)
array_ones = np.ones((10),dtype=np.ushort)
array_fives = np.full((10),5, dtype=np.ushort)
print(array_zeros)
print(array_ones)
print(array_fives)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


# Question 3:
Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array

In [106]:
a=np.full((3,3),6,dtype=np.ushort)
a[0,0:2]=5
a[1:2,0]=7
print(a)
print("Sum of all elements: ",a.sum())
print("Sum row-wise: ",a.sum(axis=0))
print("Sum column-wise: ",a.sum(axis=1))

[[5 5 6]
 [7 6 6]
 [6 6 6]]
Sum of all elements:  53
Sum row-wise:  [18 17 18]
Sum column-wise:  [16 19 18]


# Question 4:
Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [107]:
a=np.full((3,3),6,dtype=np.short)  #1st array
a[0,0:2]=5
a[1:2,0]=7

b=a.transpose()  #2nd array is populated as transpose of 1st array

print('a=\n',a,'\n','b=\n',b)
print('\n')
print("Addition: \n"+str(a+b))
print("\nSubtraction: \n"+ str(a-b))
print("\nMultiplication: \n"+str(a*b))
print("\nDivision: \n"+str(a/b))

a=
 [[5 5 6]
 [7 6 6]
 [6 6 6]] 
 b=
 [[5 7 6]
 [5 6 6]
 [6 6 6]]


Addition: 
[[10 12 12]
 [12 12 12]
 [12 12 12]]

Subtraction: 
[[ 0 -2  0]
 [ 2  0  0]
 [ 0  0  0]]

Multiplication: 
[[25 35 36]
 [35 36 36]
 [36 36 36]]

Division: 
[[1.         0.71428571 1.        ]
 [1.4        1.         1.        ]
 [1.         1.         1.        ]]


# Question 5:
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [110]:
import numpy as np
import math

angle_degrees = 90 #90degrees

to_radian = lambda deg: deg*(math.pi)/180


a=np.full((3,3),to_radian(angle_degrees),dtype=np.short) #convert to radians as reqd for sin, cos, tan

print("Sine:\n",np.sin(a))
print("\nCosine:\n",np.cos(a))
print("\nTangent:\n",np.tan(a))


Sine:
 [[0.84147096 0.84147096 0.84147096]
 [0.84147096 0.84147096 0.84147096]
 [0.84147096 0.84147096 0.84147096]]

Cosine:
 [[0.5403023 0.5403023 0.5403023]
 [0.5403023 0.5403023 0.5403023]
 [0.5403023 0.5403023 0.5403023]]

Tangent:
 [[1.5574077 1.5574077 1.5574077]
 [1.5574077 1.5574077 1.5574077]
 [1.5574077 1.5574077 1.5574077]]


# Question 6:
Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels

In [113]:
import pandas as pd
#with Index labels a,b,c
data_dict = {'name':pd.Series({'a':'ankit','b':'baskar','c':'cow'}), 'age':pd.Series({'a':1,'b':2,'c':3}),'score':pd.Series({'a':70,'b':99,'c':80})}
df = pd.DataFrame(data_dict)
print('Index Labels:',df.index)

Index Labels: Index(['a', 'b', 'c'], dtype='object')


# Question 7:
Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame

In [114]:
import pandas as pd
#Index labels a,b,c
df = pd.DataFrame({'name':pd.Series({'a':'ankit','b':'baskar','c':'cow'}), 'age':pd.Series({'a':1,'b':2,'c':3}), 'score':pd.Series({'a':70,'b':99,'c':80})})
df[['name','score']]

name  score
a   ankit     70
b  baskar     99
c     cow     80

# Question 8:
Write a Pandas program to join the two given dataframes along rows and assign all data.

In [146]:
import pandas as pd

df1 = pd.DataFrame({'name':pd.Series({'a':'ankit','b':'baskar','c':'cow'}), 'age':pd.Series({'a':1,'b':2,'c':3}), 'score':pd.Series({'a':70,'b':99,'c':80})})
df2 = pd.DataFrame({'name':pd.Series({'d':'deepak','e':'eric','f':'fani'}), 'age':pd.Series({'d':11,'e':12,'f':13}), 'score':pd.Series({'d':73,'e':93,'f':84})})

#Join along rows is a union of 2 dataframes, maintaining unique indexes
df = pd.concat([df1,df2], axis=0)
df

name  age  score
a   ankit    1     70
b  baskar    2     99
c     cow    3     80
d  deepak   11     73
e    eric   12     93
f    fani   13     84

# Question 9:
Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [135]:
import pandas as pd

def any_missing_values(df):
    missing = df.isnull().sum().sum()
    print(missing)
    return bool(missing)

print("Missing Values: ", any_missing_values(pd.DataFrame({'name':pd.Series({'a':'ankit','b':'baskar','c':'cow'}), 'age':pd.Series({'a':1,'c':3}), 'score':pd.Series({'a':70,'b':99,'c':80})})))
print("Missing Values: ", any_missing_values(pd.DataFrame({'name':pd.Series({'a':'ankit','b':'baskar','c':'cow'}), 'age':pd.Series({'a':1,'b':2,'c':3}), 'score':pd.Series({'a':70,'b':99,'c':80})})))
print("Missing Values: ", any_missing_values(pd.DataFrame({'name':pd.Series({'a':'ankit','b':'baskar','c':'cow'}), 'age':pd.Series({'a':1,'b':2,'c':3}), 'score':pd.Series({'a':70,'c':80})})))

1
Missing Values:  True
0
Missing Values:  False
1
Missing Values:  True


# Question 10:
Write a Pandas program to create and display a one-dimensional array-like object containing an array of
data.

In [137]:
import pandas as pd
import numpy as np

#Series is a one dimensional array-like object containing array of data (below is the answer)
num_series = pd.Series([1,2,3,4,5,6,7,8,9,10])
print("num_series: \n",num_series,'\nnum_series dimension: ',num_series.ndim)

#Could also create a dataframe from 1 dimension as well, which represents 1 column with shape 10x1
onedim_df = pd.DataFrame(num_series)
print("\nonedim_df: \n",onedim_df,'\nonedim_df dimension: ',onedim_df.shape)


num_series: 
 0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64 
num_series dimension:  1

onedim_df: 
     0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10 
onedim_df dimension:  (10, 1)
